### ISSUE TITLE
Will add Deserialize Trait?

### ISSUE THREAD

**Issue by baekhyunee7** [dtolnay/erased-serde#58] opened 2022-03-18 11:59 UTC
I try it:
```
pub trait IMessage<'a>:Serialize + Deserialize<'a>{

}
serialize_trait_object!(<'a> IMessage<'a>);
```
but I get error messgae: `IMessage cannot be made into an object`

**Comment by dtolnay** [comment] 2022-03-18 17:36
Closing as a duplicate of #25.

**Closed by dtolnay** 2022-03-18 17:36 UTC
